version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bn_moodle
      - POSTGRES_DB=bitnami_moodle
      - POSTGRES_PASSWORD=your_password
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  moodle:
    image: docker.io/bitnami/moodle:4.3
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=your_password
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_SITE_NAME=KidzEconomy
      - MOODLE_USERNAME=aadya
      - MOODLE_PASSWORD=aadya
    volumes:
      - "moodle_data:/bitnami/moodle"
      - "moodledata_data:/bitnami/moodledata"
      - "./theme/mytheme:/bitnami/moodle/theme/mytheme"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
